version: '3'

services:
  dashboard:
    build: .
    image: frontend2
    container_name: dashboard
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - HOST=0.0.0.0
      - PORT=3000

networks:
  app-network:
    driver: bridge 